openapi: "3.0.3"
info:
  title: "Grocerypal API"
  description: "dev API for the small grocery app"
  version: "0.0.1"
servers:
# TODO
  - url: "http://0.0.0.0:8080"
paths:
  /ingredients:
    get:
      description: "Read all ingredients"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ingredient"
              examples:
                partial:
                  value: [{"id":1,"name":"Eau","fiber":0.0,"protein":0.0,"energy":0,"carb":0.0,"fat":0.0},{"id":2,"name":"Hareng","fiber":0.0,"protein":20.1,"energy":181,"carb":0.0,"fat":11.2},{"id":3,"name":"Champignon de Paris","fiber":1.0,"protein":2.6,"energy":21,"carb":1.3,"fat":0.4},{"id":4,"name":"ail","fiber":4.7,"protein":5.81,"energy":131,"carb":21.2,"fat":0.34}]
        "500":
          description: "Internal Server Error"
  /ingredients/{id}:
    get:
      description: "Read Ingredient"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "integer"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ingredient"
              examples:
                simple_ingredient:
                  value: {"id":8,"name":"Oeuf","fiber":0.0,"protein":12.7,"energy":140,"carb":0.27,"fat":9.83}
        "404":
          description: "Not Found"
  /ingredients/from_recipe/{id}:
    get:
      description: "Read all Ingredients linked to a recipe, with their quantity"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "integer"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ingredient_Quantity"
              examples:
                simple_recipe:
                  value: [{"id":6,"name":"Bacon","fiber":0.0,"protein":39.0,"energy":476,"carb":0.5,"fat":34.1,"unitId":3,"quantity":1},{"id":8,"name":"Oeuf","fiber":0.0,"protein":12.7,"energy":140,"carb":0.27,"fat":9.83,"unitId":8,"quantity":12}]
        "404":
          description: "Not Found"
  /recipes:
    get:
      description: "Read all generic recipes"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Recipe"
              examples:
                one_recipe:
                  value: [{"id":4,"name":"Crêpes","nb_per":4,"prep_time":20,"instruction":"1 tout mettre dans un bol et mélanger \\n\r\nFaire cuire la pate dans un peu d'huile"}]
        "500":
          description: "Internal Server Error"
  /recipes/personal/{userId}:
    get:
      description: "Read all personal recipes.\n The userID requirement is temporary, and will be changed in the future"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        schema:
          type: "integer"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Recipe"
              examples:
                one_recipe:
                  value: [{"id":3,"name":"Omelette au bacon et aux champignons","nb_per":4,"prep_time":35,"instruction":"1\r\nDisposez les champignons sur une plaque recouverte de papier cuisson puis saupoudrez-les d'ail. Ajoutez 1filet d'huile dolive, du sel et du poivre, puis enfournez à 180 °C (th. 6) pour 18 à 20 min, jusqu'à ce qu'ils ramollissent. Sortez la plaque du four et laissez refroidir.\r\nPendant ce temps, disposez les tranches de bacon dans un plat recouvert de papier d'aluminium. Placez sous le gril moyennement chaud pour 5 à 6 min de cuisson, jusqu'à ce que le bacon devienne croustillant.\r\nLaissez refroidir quelques instants, puis émincez-le grossièrement.\r\nCassez les œufs dans un bol puis ajoutez la ciboulette et la moutarde. Battez l'ensemble pour le rendre homogène et assaisonnez avec un peu de poivre.\r\nFaites fondre le beurre dans une grande poêle antiadhésive pouvant aller au four.\r\nVersez les œufs battus dans la poêle, laissez cuire 1 à 2 min puis ajoutez le bacon et les champignons entiers avant de rouler l'omelette sur elle-même pour la refermer.\r\nLaissez cuire encore 2 à 3 min.\r\nMettez la poêle sous le gril chaud et laissez cuire encore 2 à 3 min. Sortez l'omelette et laissez-la refroidir un peu.\r\nParsemez de ciboulette, coupez en parts et servez."}]
        "404":
          description: "Not Found"
    post:
      description: "Add a personnal recipe.\n The userID requirement is temporary, and will be changed in the future"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          schema:
            type: "integer"
        - name: "content"
          in: "query"
          required: true
          schema:
            type: array
            items:
              $ref: "#/components/schemas/CompleteRecipe"

      responses:
        "200":
          description: "OK"
        "406":
          description: "Not Acceptable"
  /:
    get:
      description: "Service home page"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /status:
    get:
      description: "Basic status report"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Still alive!\nhttps://www.youtube.com/watch?v=VuLktUzq23c"

components:
  schemas:
    Recipe:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        nb_per:
          type: integer
          description: Number of person this recipe is made for
        prep_time:
          type: integer
          description: Preparation time, in minutes
        instruction:
          type: string
          description: Recipe instructions, formatted in markdown
    Ingredient:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        fiber:
          type: number
          description: grams of fiber per 100g
        protein:
          type: number
          description: grams of protein per 100g
        energy:
          type: integer
          description: calories
        carb:
          type: number
          description: grams of carb per 100g
        fat:
          type: number
          description: grams of fat per 100g
    Ingredient_Quantity:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        fiber:
          type: number
          description: grams of fiber per 100g
        protein:
          type: number
          description: grams of protein per 100g
        energy:
          type: integer
          description: calories
        carb:
          type: number
          description: grams of carb per 100g
        fat:
          type: number
          description: grams of fat per 100g
        unit_id:
          type: integer
          description: The unit for the quantity field
        quantity:
          type: integer
          description: The quantity of the ingredient in the list/recipe
    CompleteRecipe:
      type: object
      properties:
        recipe:
          $ref: "#/components/schemas/Recipe"
        ingredients:
          type: array
          items:
            $ref: "#/components/schemas/Quantity"
    Quantity:
      type: object
      properties:
        ingredientId:
          type: integer
        unitId:
          type: integer
        quantity:
          type: integer
