openapi: "3.0.3"
info:
  title: "Grocerypal API"
  description: "dev API for the small grocery app"
  version: "0.0.1"
servers:
# TODO
  - url: "http://0.0.0.0:8080"
paths:
  /ingredients:
    get:
      description: "Read all ingredients"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "object"
  /ingredients/{id}:
    get:
      description: "Read Ingredient"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "integer"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "object"
  /:
    get:
      description: "Hello World!"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /status:
    get:
      description: "Get the app's status"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Still alive!\nhttps://www.youtube.com/watch?v=VuLktUzq23c"
