apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    component: api
    app: grocerypal
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
      app: grocerypal 
  template:
    metadata:
      labels:
        app: grocerypal
        component: api
    spec:
      containers:
      - name: api
        image: heigpdg112023/pdg11-heig:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: POSTGRES_URL
        - name: POSTGRES_USER
          valueFrom:
           secretKeyRef:
             name: api-secret
             key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: POSTGRES_PASSWORD
